<a href="https://colab.research.google.com/github/MarcelAvgCSCoder/SYEP-Frontier-Technology-Institute-Sustainable-Energy/blob/main/SYEP_Frontier_Technology_Institute_Sustainable_Energy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

GitHub Links:  
- https://github.com/MarcelAvgCSCoder/SYEP-Frontier-Technology-Institute-Sustainable-Energy
- https://github.com/frontiertechinstitute/datasets/tree/main/Sustainable%20Energy%20Data

In [24]:
#GitHub & CSV links
github_repo_url = "https://github.com/MarcelAvgCSCoder/SYEP-Frontier-Technology-Institute-Sustainable-Energy"
github_repo_url2 = "https://github.com/frontiertechinstitute/datasets/blob/main/Sustainable%20Energy%20Data/sustainable_energy.csv"
RAW_URL = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-05-26/energy_cleaned.csv"

### *Raw Data*:

In [22]:
import pandas as pd

Sustainable_Energy = pd.read_csv('/content/sustainable_energy.csv')
print(display(Sustainable_Energy.head()))

,country_name,country_code,yr,access_non_solid_fuel_rural_pop_pct,access_non_solid_fuel_total_pop_pct,access_non_solid_fuel_urban_pop_pct,access_electricity_rural_pop_pct,access_electricity_total_pop_pct,access_electricity_urban_pop_pct,biogas_consumption_tfec_pct,...,total_final_energy_consumption_tfec,total_installed_generation_capacity_gigawatts,total_primary_energy_supply_terajoules,traditional_biomass_consumption_tfec_pct,traditional_biomass_consumption_terajoules,transmission_and_distribution_losses_pct,waste_energy_consumption_tfec_pct,waste_energy_consumption_terajoules,wind_energy_consumption_tfec_pct,wind_energy_consumption_terajoules
0,Afghanistan,AFG,1990,NaN,5.0,NaN,20.36011,34.61567,78.0,0.0,...,9661.83210,0.494,45193.24727,32.166878,3107.90970,NaN,0.0,0.0,NaN,NaN
1,Afghanistan,AFG,1991,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9229.66245,0.494,42584.16720,34.517311,3185.83125,NaN,0.0,0.0,NaN,NaN
2,Afghanistan,AFG,1992,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,8012.85660,0.494,29004.46048,41.803092,3349.62180,NaN,0.0,0.0,NaN,NaN
3,Afghanistan,AFG,1993,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9402.11415,0.494,28877.22352,37.706436,3545.20215,NaN,0.0,0.0,NaN,NaN
4,Afghanistan,AFG,1994,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9444.70035,0.494,29176.47095,39.764867,3755.67255,NaN,0.0,0.0,NaN,NaN

None

### Data Cleaning using `energy_clean_script.py`

I will now execute the provided data cleaning script to preprocess the `Sustainable_Energy` DataFrame.

In [ ]:
Energy_Clean_Data = Sustainable_Energy.copy()
del Sustainable_Energy

print("DataFrame renamed to 'Energy_Clean_Data'. Displaying its head and info:")
display(Energy_Clean_Data.head())
Energy_Clean_Data.info()

DataFrame renamed to 'Energy_Clean_Data'. Displaying its head and info:

,country_name,country_code,yr,access_non_solid_fuel_rural_pop_pct,access_non_solid_fuel_total_pop_pct,access_non_solid_fuel_urban_pop_pct,access_electricity_rural_pop_pct,access_electricity_total_pop_pct,access_electricity_urban_pop_pct,biogas_consumption_tfec_pct,...,total_final_energy_consumption_tfec,total_installed_generation_capacity_gigawatts,total_primary_energy_supply_terajoules,traditional_biomass_consumption_tfec_pct,traditional_biomass_consumption_terajoules,transmission_and_distribution_losses_pct,waste_energy_consumption_tfec_pct,waste_energy_consumption_terajoules,wind_energy_consumption_tfec_pct,wind_energy_consumption_terajoules
0,Afghanistan,AFG,1990,NaN,5.0,NaN,20.36011,34.61567,78.0,0.0,...,9661.83210,0.494,45193.24727,32.166878,3107.90970,NaN,0.0,0.0,NaN,NaN
1,Afghanistan,AFG,1991,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9229.66245,0.494,42584.16720,34.517311,3185.83125,NaN,0.0,0.0,NaN,NaN
2,Afghanistan,AFG,1992,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,8012.85660,0.494,29004.46048,41.803092,3349.62180,NaN,0.0,0.0,NaN,NaN
3,Afghanistan,AFG,1993,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9402.11415,0.494,28877.22352,37.706436,3545.20215,NaN,0.0,0.0,NaN,NaN
4,Afghanistan,AFG,1994,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,9444.70035,0.494,29176.47095,39.764867,3755.67255,NaN,0.0,0.0,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 52 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   country_name                                                       5145 non-null   object
 1   country_code                                                       5145 non-null   object
 2   yr                                                                 5145 non-null   int64
 3   access_non_solid_fuel_rural_pop_pct                                193 non-null    float64
 4   access_non_solid_fuel_total_pop_pct                                618 non-null    float64
 5   access_non_solid_fuel_urban_pop_pct                                193 non-null    float64
 6   access_electricity_rural_pop_pct                                   684 non-null    float64
 7   access_electricity_total_pop_pct                                   684 non-null    float64
 8   access_electricity_urban_pop_pct                                   680 non-null    float64
 9   biogas_consumption_tfec_pct                                        4683 non-null   float64
 10  biogas_consumption_terajoules                                      4683 non-null   float64
 11  divisia_decomp_analysis_activity_component_index                   2872 non-null   float64
 12  divisia_decomp_analysis_energy_intensity_component_index           2869 non-null   float64
 13  divisia_decomp_analysis_structure_component_index                  2869 non-null   float64
 14  energy_intensity_level_final_energy_megajoules_per_usd_2005_ppp    4102 non-null   float64
 15  energy_intensity_level_primary_energy_megajoules_per_usd_2005_ppp  4126 non-null   float64
 16  energy_intensity_agricultural_sector_megajoules_per_usd_2005       2508 non-null   float64
 17  energy_intensity_industrial_sector_megajoules_per_usd_2005         2959 non-null   float64
 18  energy_intensity_other_sectors_megajoules_per_usd_2005             2962 non-null   float64
 19  energy_savings_primary_energy_terajoules                           3933 non-null   float64
 20  final_to_primary_energy_ratio_pct                                  3224 non-null   float64
 21  geothermal_energy_consumption_tfec_pct                             1734 non-null   float64
 22  geothermal_energy_consumption_terajoules                           1756 non-null   float64
 23  hydro_energy_consumption_tfec_pct                                  3897 non-null   float64
 24  hydro_energy_consumption_terajoules                                3832 non-null   float64
 25  liquid_biofuels_energy_consumption_tfec_pct                        3134 non-null   float64
 26  liquid_biofuels_consumption_terajoules                             1482 non-null   float64
 27  marine_energy_consumption_tfec_pct                                 4683 non-null   float64
 28  marine_consumption_terajoules                                      4683 non-null   float64
 29  modern_biomass_energy_consumption_tfec_pct                         4090 non-null   float64
 30  modern_biomass_consumption_terajoules                              4077 non-null   float64
 31  perc_renewable_of_total_electricity_output                         4683 non-null   float64
 32  renewable_energy_consumption_terajoules                            4125 non-null   float64
 33  renewable_energy_consumption_tfec_pct                              4181 non-null   float64
 34  renewable_energy_electricity_output_gigawatt_hours                 4683 non-null   float64
 35  renewable_energy_installed_capacity_gigawatts                      4683 non-null   float64
 36  share_of_renewable_capacity_in_total_capacity_pct                  4496 non-null   float64
 37  solar_energy_consumption_tfec_pct                                  1912 non-null   float64
 38  solar_energy_consumption_terajoules                                1957 non-null   float64
 39  thermal_efficiency_in_power_supply_pct                             3201 non-null   float64
 40  total_electricity_output_gigawatt_hours                            4683 non-null   float64
 41  total_final_consumption_terajoules                                 4601 non-null   float64
 42  total_final_energy_consumption_tfec                                4534 non-null   float64
 43  total_installed_generation_capacity_gigawatts                      4683 non-null   float64
 44  total_primary_energy_supply_terajoules                             4637 non-null   float64
 45  traditional_biomass_consumption_tfec_pct                           4541 non-null   float64
 46  traditional_biomass_consumption_terajoules                         4683 non-null   float64
 47  transmission_and_distribution_losses_pct                           3196 non-null   float64
 48  waste_energy_consumption_tfec_pct                                  4683 non-null   float64
 49  waste_energy_consumption_terajoules                                4683 non-null   float64
 50  wind_energy_consumption_tfec_pct                                   1306 non-null   float64
 51  wind_energy_consumption_terajoules                                 1263 non-null   float64
dtypes: float64(49), int64(1), object(2)
memory usage: 2.0+ MB